### ISSUE TITLE
发现下载的 page 文件图文经常是错序的

### ISSUE THREAD

**Issue by Evandy** [eseedo/iOSCourse#1]
例如附件图片，第2篇中关于 Xcode 的一些使用指导，文字是关于控件的使用，图是源代码编译器的使用。

![screenshot 2014-11-15 15 32 28](https://cloud.githubusercontent.com/assets/4745656/5056963/4aeb438c-6cde-11e4-8e44-ad7c7eaf2d83.png)

**Comment by iplus26** [comment]
确实是错位的，而且很严重，Mac
![2015-04-17 8 39 50](https://cloud.githubusercontent.com/assets/6082721/7202128/ed27e37c-e541-11e4-82d4-aca0bcea54b2.png)

**Comment by diaosiji** [comment]
第一节和第二节会出现这个问题，后面就没有了。大家克服一下吧。

**Comment by free-memory** [comment]
有个workaround的办法,把.pages文件unzip出来,里面有个Preview.pdf,排版是正确的,只是图片不清晰.
例子:
"pages\让不懂编程的人爱上iPhone开发(2013秋iOS7版)-第2篇\QuickLook\Preview.pdf"

**Comment by iplus26** [comment]
OK 我试一下 thx
—
姜希凡 Ivan Jiang
电子科技大学 University of Electronic Science and Technology of China
Tel: (+86)186-0250-8240
Mail: iplus26@gmail.com

On Thu, Jan 28, 2016 at 7:16 PM -0800, "Ken Huang" notifications@github.com wrote:

有个workaround的办法,把.pages文件unzip出来,里面有个Preview.pdf,排版是正确的,只是图片不清晰.

例子:

"pages\让不懂编程的人爱上iPhone开发(2013秋iOS7版)-第2篇\QuickLook\Preview.pdf"
