### ISSUE TITLE
Checklists教程在Xcode6.4/iOS8.4下有一处错误

### ISSUE THREAD

**Issue by cubeland** [eseedo/iOSCourse#2]
Chapter1当中，缺少将Checklist View Controller设置为Is Initial View Controller的步骤，导致app运行后不显示任何视图，在其他版本Xcode中没有试过。

**Comment by eseedo** [comment]
你好，

多谢提醒

2015-09-09 15:43 GMT+08:00 cubeland notifications@github.com:

**Comment by bitgxd** [comment]
在ios8下编译出现 Unknown class ChecklistsViewController in Interface Builder file.

**Comment by bitgxd** [comment]
第三篇中cellForRowAtIndexPath方法下，最后check弄反了，应该是
if(isChecked){
cell.accessoryType = UITableViewCellAccessoryCheckmark
}else{
cell.accessoryType = UITableViewCellAccessoryNone;

**Comment by eseedo** [comment]
多谢提醒，看来我该把obj-c版本的教程也升级了，哎
iOS9+Swift2+Xcode7的版本请移步我的博客或者知乎专栏（zhuanlan.zhihu.com/kidscoding)

**Comment by jameshpy** [comment]
谢谢

在 2015-10-20 00:17:05，"bitgxd" notifications@github.com 写道：

在cellForRowAtIndexPath方法下，最后check弄反了，应该是
if(isChecked){
cell.accessoryType = UITableViewCellAccessoryCheckmark
}else{
cell.accessoryType = UITableViewCellAccessoryNone;

**Comment by bitgxd** [comment]
第二个项目 第16篇中在AllListsViewController.m中添加⼀一个accessoryButtonTappedForRowWithIndexPath ⽅方法。该⽅方法来⾃自表视图的代理协议,看这个名字你差不多就知道它的作⽤用了。用代码实现segue，打开Edit Checklist，还需要在TableViewCell中添加
cell.accessoryType = UITableViewCellAccessoryDetailDisclosureButton;
才能看见可以点击编辑的accessoryButton
